# Generated by Django 3.2 on 2023-02-17 16:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_alter_marketsector_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
