# Generated by Django 3.2 on 2023-02-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('utility', '0001_initial'),
        ('platform_admin', '0004_alter_historical_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoPoliticalCategory',
            new_name='GeoPhysicalCategory',
        ),
        migrations.RenameModel(
            old_name='GeoPoliticalData',
            new_name='GeoPhysicalData',
        ),
    ]
