# Generated by Django 3.2 on 2023-02-20 05:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0005_auto_20230220_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geophysicaldata',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
