# Generated by Django 3.2 on 2023-02-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0006_alter_geophysicaldata_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSectorSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_admin.marketsectorcategory')),
            ],
            options={
                'verbose_name_plural': 'Market Sector Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='marketsectorbulkdata',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_admin.marketsectorsubcategory'),
        ),
    ]
