# Generated by Django 3.2 on 2023-02-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0007_auto_20230226_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketsector',
            name='address_location',
        ),
        migrations.RemoveField(
            model_name='marketsector',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marketsector',
            name='phone_number',
        ),
    ]
