# Generated by Django 3.2 on 2023-02-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0008_auto_20230226_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_admin.marketsectorsubcategory'),
        ),
    ]
