# Generated by Django 3.2 on 2023-03-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0009_marketsector_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geophysicalcategory',
            options={'verbose_name_plural': 'Geo Physical Categories'},
        ),
    ]
