# Generated by Django 3.2 on 2023-03-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_subclan'),
        ('platform_admin', '0010_alter_geophysicalcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='geophysicaldata',
            name='subclan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.subclan'),
        ),
        migrations.AddField(
            model_name='historical',
            name='subclan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.subclan'),
        ),
        migrations.AddField(
            model_name='marketsector',
            name='subclan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.subclan'),
        ),
    ]
