# Generated by Django 3.2 on 2023-06-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0011_auto_20230303_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='geophysicalcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geophysicaldata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historical',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketsector',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketsectorbulkdata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketsectorcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketsectorsubcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
