# Generated by Django 3.2 on 2023-08-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0012_auto_20230613_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsectorsubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='platform_admin.marketsectorcategory'),
        ),
    ]
