# Generated by Django 3.2 on 2024-07-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_auto_20230815_1526'),
        ('search_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdata',
            name='geo_political_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.geopoliticalzone'),
        ),
    ]
