# Generated by Django 3.2 on 2024-07-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0002_alter_searchdata_geo_political_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='other_references',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchdata',
            name='visualization_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SearchDataVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_data.searchdata')),
            ],
        ),
        migrations.CreateModel(
            name='SearchDataNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_data', models.URLField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_data.searchdata')),
            ],
        ),
        migrations.CreateModel(
            name='SearchDataMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_data', models.URLField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_data.searchdata')),
            ],
        ),
        migrations.CreateModel(
            name='SearchDataImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_data.searchdata')),
            ],
        ),
    ]
