# Generated by Django 3.2 on 2024-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0003_auto_20240718_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
