# Generated by Django 3.2 on 2024-07-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0004_searchdata_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, choices=[('historical', 'Historical'), ('market', 'Market'), ('geophysical', 'Geophysical')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchDataSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, choices=[('historical', 'Historical'), ('market', 'Market'), ('geophysical', 'Geophysical')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_data.searchdatacategory')),
            ],
        ),
        migrations.AddField(
            model_name='searchdata',
            name='data_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_data.searchdatacategory'),
        ),
        migrations.AddField(
            model_name='searchdata',
            name='data_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_data.searchdatasubcategory'),
        ),
    ]
