# Generated by Django 3.2 on 2024-07-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0005_auto_20240718_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchdataimages',
            old_name='main_video',
            new_name='main_image',
        ),
    ]
