# Generated by Django 3.2 on 2024-07-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230918_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_analyze_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_data_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_geographical_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_historical_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_market_sector_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_stored_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_analytics_tools',
            field=models.BooleanField(default=False),
        ),
    ]
