# Generated by Django 3.2 on 2024-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240719_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='who_can_find_me',
            field=models.CharField(blank=True, choices=[('everyone', 'Everyone'), ('users', 'Users')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_message_me',
            field=models.CharField(blank=True, choices=[('everyone', 'Everyone'), ('users', 'Users')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_share_data_with_me',
            field=models.CharField(blank=True, choices=[('everyone', 'Everyone'), ('users', 'Users')], max_length=50, null=True),
        ),
    ]
