# Generated by Django 3.2 on 2023-02-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('utility', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='city_managers', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='clan',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='clan_managers', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='geopoliticalzone',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='geo_political_zone_managers', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='state',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='state_managers', to='accounts.Profile'),
        ),
    ]
