# Generated by Django 3.2 on 2023-03-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('utility', '0003_auto_20230227_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='restricted_users',
            field=models.ManyToManyField(blank=True, related_name='clan_restricted_users', to='accounts.Profile'),
        ),
    ]
