# Generated by Django 3.2 on 2023-03-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('utility', '0004_clan_restricted_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.clan')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.country')),
                ('geo_political_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.geopoliticalzone')),
                ('managers', models.ManyToManyField(blank=True, related_name='subclan_managers', to='accounts.Profile')),
                ('restricted_users', models.ManyToManyField(blank=True, related_name='subclan_restricted_users', to='accounts.Profile')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
