# Generated by Django 3.2 on 2023-04-17 11:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_auto_20230416_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
