# Generated by Django 3.2 on 2023-08-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_auto_20230613_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_countries', to='utility.country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='geo_political_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_geo_political_zones', to='utility.geopoliticalzone'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_states', to='utility.state'),
        ),
        migrations.AlterField(
            model_name='city',
            name='tribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_tribes', to='utility.tribe'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_cities', to='utility.city'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_countries', to='utility.country'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='geo_political_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_geo_political_zones', to='utility.geopoliticalzone'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_states', to='utility.state'),
        ),
        migrations.AlterField(
            model_name='geopoliticalzone',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_political_zone_countries', to='utility.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_countries', to='utility.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='geo_political_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_geo_political_zones', to='utility.geopoliticalzone'),
        ),
    ]
