# Generated by Django 3.2.25 on 2026-09-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_auto_20230815_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clan',
            options={'ordering': ['name'], 'verbose_name_plural': 'Clans'},
        ),
        migrations.AlterModelOptions(
            name='subclan',
            options={'ordering': ['name'], 'verbose_name_plural': 'Sub-Clans / Territorial Nodes'},
        ),
        migrations.AddField(
            model_name='clan',
            name='code',
            field=models.CharField(blank=True, help_text='Territory code prefix, e.g. RUM', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='node_id',
            field=models.CharField(blank=True, db_index=True, help_text='Territorial Node ID, e.g. RUM-CLN-001', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subclan',
            name='node_id',
            field=models.CharField(blank=True, db_index=True, help_text='PRD pattern: [Territory]-[Node Type]-[Sequential Number], e.g. RUM-ST-001', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subclan',
            name='node_type',
            field=models.CharField(choices=[('STREET', 'Street (ST)'), ('CLOSE', 'Close / Crescent (CL)'), ('LINK_ROAD', 'Sub / Link Road (RD)'), ('META_ROAD', 'Meta Road (RD)'), ('COMMUNITY', 'Community / Village (COM)'), ('BUILDING', 'Building (BLD)'), ('BUSINESS', 'Business (BIZ)'), ('FACILITY', 'Facility (FAC)'), ('LANDMARK', 'Landmark (LMK)'), ('OTHER', 'Other Territorial Node (NOD)')], default='STREET', help_text='Territorial node classification', max_length=50),
        ),
    ]
