# Generated by Django 3.2.25 on 2026-09-25 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_auto_20260924_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_cities', to='utility.city'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_countries', to='utility.country'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='geo_political_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_geo_political_zones', to='utility.geopoliticalzone'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_states', to='utility.state'),
        ),
        migrations.AlterField(
            model_name='subclan',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city'),
        ),
        migrations.AlterField(
            model_name='subclan',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.country'),
        ),
        migrations.AlterField(
            model_name='subclan',
            name='geo_political_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.geopoliticalzone'),
        ),
        migrations.AlterField(
            model_name='subclan',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.state'),
        ),
    ]
