# Generated by Django 3.2.25 on 2026-09-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_auto_20260925_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclan',
            name='parent_road',
            field=models.ForeignKey(blank=True, help_text='Major road, meta road, or link road this street/close connects to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_streets', to='utility.subclan'),
        ),
        migrations.AddField(
            model_name='subclan',
            name='road_condition',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent (Newly Paved / No Potholes)'), ('GOOD', 'Good (Minor Wear / Fully Motorrable)'), ('FAIR', 'Fair (Moderate Potholes / Motorrable with Caution)'), ('POOR', 'Poor (Severe Potholes / Eroded)'), ('CRITICAL', 'Critical / Impassable / Flooded')], default='GOOD', help_text='Overall condition of the road', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subclan',
            name='road_surface',
            field=models.CharField(blank=True, choices=[('ASPHALT', 'Paved / Asphalt'), ('INTERLOCKED', 'Interlocked Paving Stones'), ('CONCRETE', 'Rigid Concrete Pavement'), ('EARTH_ROAD', 'Unpaved / Earth / Laterite'), ('GRAVEL', 'Gravel / Crushed Stone'), ('DILAPIDATED', 'Dilapidated / Failed Road'), ('OTHER', 'Other Surface')], default='ASPHALT', help_text='Surface type of the road (e.g. Asphalt, Interlocked, Earth)', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TerritorialInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Concrete Covered Drainage - East Side, 50W Solar Streetlights Section A', max_length=255)),
                ('infrastructure_type', models.CharField(choices=[('DRAINAGE', 'Drainage / Storm Water Channel'), ('STREET_LIGHT', 'Street Lighting (Solar / Grid)'), ('POWER_TRANSFORMER', 'Power Transformer / Distribution Grid'), ('WATER_SUPPLY', 'Public Water Supply / Borehole Tap'), ('SECURITY_POST', 'Security Gate / Checkpoint / Barrier'), ('WASTE_DISPOSAL', 'Waste Disposal / Dump Point'), ('SIDEWALK', 'Sidewalk / Pedestrian Walkway'), ('SPEED_BUMP', 'Speed Bumps / Traffic Calming'), ('TELECOM_INFRASTRUCTURE', 'Telecom Mast / Fiber Distribution Box'), ('BRIDGE_CULVERT', 'Bridge / Culvert / Canal Crossing'), ('TRAFFIC_LIGHT', 'Traffic Light / Signal'), ('OTHER', 'Other Territorial Infrastructure')], max_length=50)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational / Good Condition'), ('NEEDS_MAINTENANCE', 'Needs Maintenance / Minor Repairs'), ('CRITICAL', 'Damaged / Dysfunctional / Flooded'), ('UNDER_CONSTRUCTION', 'Under Construction / In Progress'), ('ABANDONED', 'Abandoned / Defunct')], default='OPERATIONAL', max_length=50)),
                ('side_of_road', models.CharField(blank=True, choices=[('BOTH', 'Both Sides of Road'), ('LEFT', 'Left Side'), ('RIGHT', 'Right Side'), ('MEDIAN', 'Median / Center Island'), ('INTERSECTION', 'Intersection / Crossing'), ('NOT_APPLICABLE', 'Not Applicable')], default='BOTH', max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units, e.g. 15 street light poles')),
                ('coverage_length_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Coverage or length in meters (e.g. for drainage, sidewalk)', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('installed_by', models.CharField(blank=True, help_text='e.g. State Government, Community Self-Help, Federal Ministry, Private Developer', max_length=255, null=True)),
                ('year_installed', models.PositiveIntegerField(blank=True, null=True)),
                ('gps_coordinates', models.CharField(blank=True, help_text='Latitude, Longitude (e.g. 4.8156, 7.0498)', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_infrastructures', to='utility.clan')),
                ('subclan', models.ForeignKey(blank=True, help_text='Specific road/street or territorial node where this infrastructure is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='utility.subclan')),
            ],
            options={
                'verbose_name': 'Territorial Infrastructure',
                'verbose_name_plural': 'Territorial Infrastructures',
                'ordering': ['-date_created'],
            },
        ),
    ]
