# Generated by Django 3.2.25 on 2026-10-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0012_auto_20260930_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='node_id',
            field=models.CharField(blank=True, db_index=True, help_text='Territorial Node ID, e.g. NG/SS/RIV/OBIO-AKPOR/CLN/001', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subclan',
            name='node_id',
            field=models.CharField(blank=True, db_index=True, help_text='Territorial Node ID, e.g. NG/SS/RIV/OBIO-AKPOR/CLN/001/SB/001', max_length=150, null=True),
        ),
    ]
