# Generated by Django 3.2.25 on 2026-10-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0013_auto_20261005_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclan',
            name='node_type',
            field=models.CharField(choices=[('MAJOR_ROAD', 'Major Road (MR)'), ('SUB_ROAD', 'Sub Road (SR)'), ('STREET', 'Street (STR)'), ('CLOSE', 'Close / Crescent (CLS)'), ('SUB_CLAN', 'Sub-Clan / Community (SB)'), ('COMMUNITY', 'Community / Village (SB)'), ('LINK_ROAD', 'Sub / Link Road (SR)'), ('META_ROAD', 'Meta Road (MR)'), ('BUILDING', 'Building (BLD)'), ('BUSINESS', 'Business (BIZ)'), ('FACILITY', 'Facility (FAC)'), ('LANDMARK', 'Landmark (LMK)'), ('OTHER', 'Other Territorial Node (NOD)')], default='STREET', help_text='Territorial node classification', max_length=50),
        ),
    ]
