"""
Django settings for ennga project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from datetime import timedelta
from decouple import config
from pathlib import Path
from urllib.parse import urlparse, unquote, parse_qs


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pud1ka-bnw5$d=-yp-$=#x_for3s^72-vd&s*nn8*1+$0enepf'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'crispy_forms',
    # 'multiselectfield',
    'widget_tweaks',
    "anymail",
    'django_htmx',
    'ckeditor',
    'ckeditor_uploader',
    'phonenumber_field',


    'rest_framework',
    'allauth.socialaccount',
    'rest_framework.authtoken',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    
    "django_elasticsearch_dsl",
    "django_elasticsearch_dsl_drf",
    "drf_yasg",

    'accounts',
    'utility',
    'public',
    'platform_admin',
    'search_data',
]

# Custom user model
AUTH_USER_MODEL = 'accounts.Account'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',

]

ROOT_URLCONF = 'ennga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ennga.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASE_URL = (
    config("DATABASE_URL", default="").strip().strip("\"'")
    or config("PROD_DATABASE_URL", default="").strip().strip("\"'")
)
DB_NAME = config("DB_NAME", default="").strip().strip("\"'")

# Check if SSH Tunnel is active (for Namecheap cPanel remote MySQL on Render)
USE_SSH_TUNNEL = (
    config("USE_SSH_TUNNEL", default=False, cast=bool)
    or config("SSH_TUNNEL", default=False, cast=bool)
)
SSH_LOCAL_HOST = config("SSH_LOCAL_HOST", default="127.0.0.1")
SSH_LOCAL_PORT = str(config("SSH_LOCAL_PORT", default="3306"))

if DATABASE_URL:
    url = urlparse(DATABASE_URL)
    query_params = parse_qs(url.query)
    scheme = url.scheme.lower()

    if "postgres" in scheme:
        engine = "django.db.backends.postgresql"
        default_port = 5432
    elif "mysql" in scheme:
        engine = "django.db.backends.mysql"
        default_port = 3306
    elif "sqlite" in scheme:
        engine = "django.db.backends.sqlite3"
        default_port = None
    else:
        engine = scheme
        default_port = 5432

    options = {}
    if "mysql" in engine:
        options["charset"] = "utf8mb4"

    # Extract sslmode if present or if Prisma / Supabase / Neon / Render
    sslmode = query_params.get("sslmode", [None])[0]
    if sslmode:
        options["sslmode"] = sslmode
    elif "postgres" in engine and any(cloud in (url.hostname or "") for cloud in ["prisma.io", "render.com", "supabase", "neon.tech"]):
        options["sslmode"] = "require"

    db_config = {
        "ENGINE": engine,
        "NAME": unquote(url.path.lstrip("/")),
        "USER": unquote(url.username or ""),
        "PASSWORD": unquote(url.password or ""),
        "HOST": url.hostname or "localhost",
        "PORT": str(url.port or default_port or ""),
        "CONN_MAX_AGE": config("DB_CONN_MAX_AGE", default=0, cast=int),
    }
    if options:
        db_config["OPTIONS"] = options

    # For poolers (Prisma Postgres pooled, Supabase pooler, Neon, pgBouncer):
    # Disable server side cursors to prevent transaction pooler issues
    if "pooled" in (url.hostname or "") or "pgbouncer" in query_params or "pgbouncer=true" in DATABASE_URL.lower():
        db_config["DISABLE_SERVER_SIDE_CURSORS"] = True

    # If SSH tunnel is enabled, redirect database traffic to the local tunnel endpoint
    if USE_SSH_TUNNEL:
        db_config["HOST"] = SSH_LOCAL_HOST
        db_config["PORT"] = int(SSH_LOCAL_PORT) if str(SSH_LOCAL_PORT).isdigit() else SSH_LOCAL_PORT

    DATABASES = {
        "default": db_config
    }
elif DB_NAME:
    db_engine_env = config("DB_ENGINE", default="mysql").lower()
    if "mysql" in db_engine_env:
        engine = "django.db.backends.mysql"
        default_port = "3306"
        options = {'charset': 'utf8mb4'}
    elif "postgres" in db_engine_env:
        engine = "django.db.backends.postgresql"
        default_port = "5432"
        options = {}
    elif "sqlite" in db_engine_env:
        engine = "django.db.backends.sqlite3"
        default_port = None
        options = {}
    else:
        engine = db_engine_env
        default_port = "3306"
        options = {}

    db_host = config("DB_HOST", default="localhost")
    db_port = str(config("DB_PORT", default=default_port or '3306'))

    if USE_SSH_TUNNEL:
        db_host = SSH_LOCAL_HOST
        db_port = SSH_LOCAL_PORT

    DATABASES = {
        'default': {
            'ENGINE': engine,
            'NAME': DB_NAME,
            'USER': config("DB_USER", default="root"),
            'PASSWORD': config("DB_PASSWORD", default=""),
            'HOST': db_host,
            'PORT': db_port,
        }
    }
    if options:
        DATABASES['default']['OPTIONS'] = options
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

#beginning
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_in_env')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#end

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


############################################### Beginning of Development ########################################

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL='Ennga.com <ennga@kulenga.org>' 

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MAILJET_API_KEY = config("MAILJET_API_KEY", default="")
MAILJET_SECRET_KEY = config("MAILJET_SECRET_KEY", default="")

# Mailjet settings
if MAILJET_API_KEY and MAILJET_SECRET_KEY:
    EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
    ANYMAIL = {
        "MAILJET_API_KEY": MAILJET_API_KEY,
        "MAILJET_SECRET_KEY": MAILJET_SECRET_KEY,
    }
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default="")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="")
AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default="")
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="")

if AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_QUERYSTRING_AUTH = False
    AWS_QUERYSTRING_EXPIRE = 60*60*24*365*10
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

############################################### End of Development ########################################

SITE_URL = 'https://ennga.com'

SITE_ID = 1

# CELERY SETTINGS
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
# CELERY_BROKER_URL = 'rediss://:pa4cd541ac58e26357078bdf9d04b5b65be73f2f18cd66d5840e4dc1513db97cd@ec2-34-193-69-177.compute-1.amazonaws.com:19720'

# DRF 
CORS_ALLOW_ALL_ORIGINS = True

CRISPY_TEMPLATE_PACK = 'bootstrap4'

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'height': 'full', 
        'width': 'full', 
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ],
    
    'TEST_REQUEST_RENDERER_CLASSES': [
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer'
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
        'PAGE_SIZE': 100
}

REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.UserDetailsSerializer'
}
ELASTIC_USER = config("ELASTIC_USER")
ELASTIC_PASSWORD = config("ELASTIC_PASSWORD")

ELASTICSEARCH_DSL = {
    "default": {
        "hosts": "http://localhost:9200",
        "http_auth": (ELASTIC_USER, ELASTIC_PASSWORD),
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=4320),  # 3 Days
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=15),
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=21600),
    "SLIDING_TOKEN_REFRESH_LIFETIME_GRACE_PERIOD": timedelta(days=30),
    "SLIDING_TOKEN_REFRESH_SYNC_REFRESH": False,
    "SLIDING_TOKEN_REFRESH_EPOCHAL_REFRESH": False,
    "SLIDING_TOKEN_REFRESH_STRATEGY": "keep",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    # Token blacklist settings
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
}